featureSet: TechPreviewNoUpgrade
additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: ite.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ite-ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.10.15.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIPs:
    - 10.10.15.122
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: vcsa01.seit.local
      topology:
        computeCluster: /VxRail-Datacenter/host/VxRail-Virtual-SAN-Cluster
        datacenter: VxRail-Datacenter
        datastore: /VxRail-Datacenter/datastore/VxRail-Virtual-SAN-Datastore
        networks:
        - INT_VDI-VLAN15
        resourcePool: /VxRail-Datacenter/host/VxRail-Virtual-SAN-Cluster/Resources
      zone: generated-zone
    ingressVIPs:
    - 10.10.15.123
    hosts:
    - role: bootstrap
      networkDevice:
        ipAddrs:
        - 10.10.15.115/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.10.15.116/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.10.15.117/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    - role: control-plane
      networkDevice:
        ipAddrs:
        - 10.10.15.118/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    - role: compute
      networkDevice:
        ipAddrs:
        - 10.10.15.119/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    - role: compute
      networkDevice:
        ipAddrs:
        - 10.10.15.120/24
        gateway: 10.10.15.1
        nameservers:
        - 10.10.15.112
    vcenters:
    - datacenters:
      - VxRail-Datacenter
      password: Redact
      port: 443
      server: vcsa01.seit.local
      user: administrator@vsphere.local
publish: External
pullSecret: Redact
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCagVQ4lGASKgqZ926Ux2oSI8ZhqJZLCT/yQDxxGCwnvZj4SaojspcvSyi/Bq+LTnYX7jx4DKIpbGukXOehffLPSXVpn02ip3CLxolQYtlGZBlEyLsbGjxmuMe6+fmVgGTxd2p4LK2KWNDPmNW8AuxhZUw5y2P7eWl4jWZKWLqNfDNoTgWbDOM4O69kbctwtAyQKDWpW2O12icNyuBDPVZsjaQYQOKyTz5B/CvC/sc46Fuhm5O/mohujE2SVdialbbzIDc0/qvFctDxqqpoO0SMlf3aw3aPZnirlqLGoqRvG8yglfg4b/Te7LWnhrewvHWj2qRJAl3vZST75IVEBPXA1kFZSoD2t46Nx6FnnlC86Tjy315drMY40jc/0u+ZgChs4KoLFpEqYdkcftiVaRI3cqj3RxIMwrrExDTd3qWMKTJS1E9SCL2+v4lz5TYrsm4MQb2QXKkN4lRHxe6xQZhllJjwCiRoTRsGZGu+XZeSRypLagqIM9a+1AtrwNrj9APNk4bYPLLIICNjusXsKdsiCuQegPzKC80n0TAeZJyuCqmggNhvrqsToru82nYaQDyVzS76W50ZPBj8KE3snN9NtaUI1ikGe34gkv8IlgIpTf16e++YFXky/rf/4zcyLMhSzUQAYwYarFZbS3Kx78uVaDOb5C0SKq7IOadYrybU7Q== isngpu01@seit.local@debian01.seit.local

