---

- name: Enable of Ethernet
  hosts: ios
  gather_facts: false
  tasks:
     - name: Ensure Ethernet2 interface is enabled (no shutdown)
       cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet2
            description: "Enabled by SEIT"
          - name: Loopback1
            description: "Enabled by SEIT"
        state: merged

- name: Assign IP address for IOSEX1
  hosts: itecc
  tasks:
    - name: Assign IP address
      cisco.ios.ios_l3_interfaces:
        config:
         - name: GigabitEthernet2
           ipv4:
             - address: 10.10.10.1/30
         - name: Loopback1
           ipv4:
             - address: 172.168.10.5/24
        state: merged
  
- name: Assign IP address for IOSEX2
  hosts: itecw
  tasks:
    - name: Assign IP address
      cisco.ios.ios_l3_interfaces:
         config:
          - name: GigabitEthernet2
            ipv4:
            - address: 10.10.10.2/30
          - name: Loopback1
            ipv4:
            - address: 172.169.10.5/24
         state: merged